// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type TestUser struct {
	ID        interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
